CC = gcc
TARGET = staticVariable2.out
OBJS = staticVariable2.o
SRCS = staticVariable2.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS) -lm

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
