CC = gcc
TARGET = BinarySearch.out
OBJS = BinarySearch.o
SRCS = BinarySearch.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(TARGET)
	rm $(OBJS)

