CC = gcc
TARGET = pointerOperation.out
OBJS = pointerOperation.o
SRCS = pointerOperation.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
