CC = gcc
TARGET = escape_Switch.out
OBJS = escape_Switch.o
SRCS = escape_Switch.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(TARGET)
	rm $(OBJS)
