CC = gcc
TARGET = design_strcmp.out
OBJS = design_strcmp.o
SRCS = design_strcmp.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
