CC = gcc
TARGET = SwapOperator.out
OBJS = SwapOperator.o
SRCS = SwapOperator.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS) -lm

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
