CC = gcc
TARGET = globaVariable.out
OBJS = globalVarialbe.o
SRCS = globalVariable.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
