CC = gcc
TARGET = CommandExecution.out
OBJS = ComandExecution.o
SRCS = CommandExecution.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
