CC = gcc
TARGET = Rectangle_Area.out
OBJS = Rectangle_Area.o
SRCS = Rectangle_Area.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
